// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Xgts_tSLyAowT5i-GuTPQMI6ygZKQ1U',
    appId: '1:47092569691:web:0318b54c3d8533e531917e',
    messagingSenderId: '47092569691',
    projectId: 'movie-app-fe597',
    authDomain: 'movie-app-fe597.firebaseapp.com',
    storageBucket: 'movie-app-fe597.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6sUhVOn7eOWWsO69P9QTyqdS7TeFulY0',
    appId: '1:47092569691:android:d63478508ba6625631917e',
    messagingSenderId: '47092569691',
    projectId: 'movie-app-fe597',
    storageBucket: 'movie-app-fe597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjg4aHeHwOgzsWHbfglg--ichQtqgzM8',
    appId: '1:47092569691:ios:e3173f990446ea3531917e',
    messagingSenderId: '47092569691',
    projectId: 'movie-app-fe597',
    storageBucket: 'movie-app-fe597.appspot.com',
    iosClientId: '47092569691-9hvnkmpvu3p63bnqsmcqb3fgbht98j93.apps.googleusercontent.com',
    iosBundleId: 'com.example.mileTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjg4aHeHwOgzsWHbfglg--ichQtqgzM8',
    appId: '1:47092569691:ios:aacf205e668e59ec31917e',
    messagingSenderId: '47092569691',
    projectId: 'movie-app-fe597',
    storageBucket: 'movie-app-fe597.appspot.com',
    iosClientId: '47092569691-djja5dafa4fri3jm3ohjqmriqo3jij3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mileTwo.RunnerTests',
  );
}
